### ISSUE TITLE
White Screen of Death 

### ISSUE THREAD

**Issue by tobysteward** [keithclark/selectivizr#13]
First of all, fantastic work with Selectivizr! I've applied it to many sites and found it incredibly useful.

Currently I'm having an issue with IE8 intermitantely white-screen-of-death'ing when Selectivizr is included in the site. The site is quite big and there's a lot of other JavaScript so it could be an issue with compatiability? 

The site in question is puregym dot com and the WSOD is happening intermittantely on XP based PCs - it mainly seems to be happening to our kiosk machines but it has been happening on our usual desktops too.

**Comment by keithclark** [comment]
Is the site using @font-face? There seems to be a link to "WSOD" when using css fonts.

**Comment by tobysteward** [comment]
Hi Keith,

We are indeed using @font-face across a few of the headers. I linked the site in my original post uptop if you have a free minute to check it out. Does the issue seem to happen with other font solutions (TypeKit, Cufan)?

**Comment by keithclark** [comment]
I'm beginning to suspect @font-face is the issue here but it's proving a pain to create tests that consistently reproduce this behaviour so I can draw conclusions from them. I'm not sure if font providers will produce different results either.

**Comment by tobysteward** [comment]
I agree; the WSODs seem intermittent at best however I managed to recreate the error on 22 kiosk systems using a IE wrapper. I stripped out font-face that seems to have fixed it, aside from the kiosks I haven't been able to reproduce the WSOD - although we did have reports of it happening on home users PCs.

**Comment by keithclark** [comment]
Issue fixed in this commit: 56d83b4666dd76379de6ec2d223f8b9022f865a4

**Comment by johnnycadelco** [comment]
Keith can you reopen this ticket?  I'm still getting WSODs even with the latest version.

**Comment by jrtowell** [comment]
Also getting WSOD on IE8 with 1.03b.

**Comment by dstrojny** [comment]
Also still seeing WSOD in IE8 with @font-face.

**Comment by FlyingDR** [comment]
I've put some analysis [here](https://github.com/keithclark/selectivizr/issues/30#issuecomment-5379856), also it looks like there is workaround for the problem that works for me with both 1.0.2 and 1.0.3b

**Comment by johnnycadelco** [comment]
FlyingDR thanks man! hopefully they fix it.

**Comment by feeela** [comment]
@keithclark Please re-open, as this issue is not fixed in lastest versions of selectivizr. We can't alter our CSS in each case, just to get support for some dying browser. This should be fixed in selectivizr – not through some workaround that requires a fixed sorting of includes.
